[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "spyglass-neuro"
version = "0.3.4"
authors = [
    { name = "Loren Frank", email = "loren.frank@ucsf.edu" },
    { name = "Kyu Hyun Lee", email = "kyuhyun.lee@ucsf.edu" },
    { name = "Eric Denovellis", email = "eric.denovellis@ucsf.edu" },
    { name = "Ryan Ly", email = "rly@lbl.gov" },
]
description = "Neuroscience data analysis framework for reproducible research"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8,<3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = [
    "neuroscience",
    "research",
    "electrophysiology",
    "reproducible",
    "data analysis",
    "spike sorting",
    "spikeinterface",
    "datajoint",
    "nwb",
    "kachery",
    "sortingview",
]
dependencies = [
    "pydotplus",
    "dask",
    "position_tools",
    "track_linearization>=2.3",
    "replay_trajectory_classification",
    "ripple_detection",
    "trajectory_analysis_tools",
    "matplotlib",
    "seaborn",
    "skan",
    "bottleneck",
    "ipympl",
    "tqdm",
    "pubnub<6.4.0",
    "pynwb>=2.2.0,<3",
    "hdmf>=3.4.6",
    "datajoint>=0.13.6",
    "pymysql",
    "sortingview>=0.11",
    "pyyaml",
    "click",
    "spikeinterface",
    "ndx_franklab_novela>=0.1.0",
]

[project.scripts]
spyglass_cli = "spyglass.cli:cli"

[project.urls]
"Homepage" = "https://github.com/LorenFrankLab/spyglass"
"Bug Tracker" = "https://github.com/LorenFrankLab/spyglass/issues"

[tool.black]
# line-length = 120
